# Refer here for all the supported options for VaultAuth Custom Resource
# https://raw.githubusercontent.com/hashicorp/vault-secrets-operator/main/chart/crds/secrets.hashicorp.com_vaultstaticsecrets.yaml

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: demo-ns
spec:
  type: kv-v1

  # mount path
  mount: kv

  # path of the secret
  path: webapp/config

  # dest k8s secret
  destination:
    name: secret-kv
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth