---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultPKISecret
metadata:
  name: vaultpkisecret-tls
  namespace: demo-ns
spec:
  # vaultAuthRef: vaultauth-sample
  # namespace: demo-ns
  mount: pki
  name: default
  destination:
    create: true
    name: pki-tls
    type: kubernetes.io/tls
  commonName: localhost
  format: pem
  revoke: true
  clear: true
  expiryOffset: 15s
  ttl: 1m